clever_tech_front:
    resource: "@CleverTechFrontBundle/Controller"
    type: annotation
    prefix: /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"