services:
    sonata.admin.portfolio:
        class: CleverTech\FrontBundle\Admin\PortfolioAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Dane", label: "Projekty" }
        arguments:
            - ~
            - CleverTech\FrontBundle\Entity\Portfolio
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
    sonata.admin.worker:
        class: CleverTech\FrontBundle\Admin\WorkerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Dane", label: "Pracownicy" }
        arguments:
            - ~
            - CleverTech\FrontBundle\Entity\Worker
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]